name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler cmake

    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu --features "browser,rustls-tls-webpki-roots"

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install protoc
      run: |
        choco install protoc --version=3.14.0

    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-msvc --features "browser,rustls-tls-webpki-roots"
