 name: Build and Upload Artifacts

 on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

 jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         target: [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-musl" ]
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Install dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y build-essential protobuf-compiler llvm

       - name: Install Rust
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           target: ${{ matrix.target }}
           profile: minimal

       - name: Add Rust target
         run: rustup target add ${{ matrix.target }}

       - name: Build project
         run: cargo build --release --target ${{ matrix.target }}

       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: vsd-${{ matrix.target }}
           path: target/${{ matrix.target }}/release/vsd
