name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r22b-linux-x86_64.zip
          unzip android-ndk-r22b-linux-x86_64.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r22b
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Add rust target
        run: rustup target add aarch64-linux-android

      - name: Build for Android
        run: |
          RUSTFLAGS="-C link-args=-Wl,-rpath=/data/data/com.termux/files/usr/lib -C link-args=-Wl,--enable-new-dtags" \
          cargo build -p vsd --release --target aarch64-linux-android
