name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/@v3
      
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
       : rustfmt
        target: ${{ matrix.target }}
        profile: minimal

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y protobufcompiler cmake clang

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install protobuf cmake clang

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install protoc
        choco install cmake
        choco install llvm

    - name: Build the project
      run: |
        cargo build --release

 - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vsd-${ matrix.os }}
        path: target/release/*
